import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Clientprovider from "@/components/Clientprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "personal site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Clientprovider>
        {children}
        </Clientprovider>
        </body>
    </html>
  );
}
